<?php

// all possible options will be stored
$config = array();

// a unique key that identifies this application - DO NOT LEAVE THIS EMPTY!
$config['app_key'] = '';

// a secret key to be used during encryption
$config['encryption_key'] = '';

// URL running the proxy app
//$config['app_url'] = 'https://www.mysampleproxy.com/proxyfolder/';

/*
how unique is each URL that is generated by this proxy app?
0 - no encoding of any sort. People can link to proxy pages directly: ?q=http://www.yahoo.com
1 - Base64 encoding only, people can hotlink to your proxy
2 - unique to the IP address that generated it. A person that generated that URL, can bookmark it and visit it and any point
3 - unique to that session and IP address - URL no longer valid anywhere when that browser session that generated it ends
*/

$config['url_mode'] = 2;

// Disabling PHP session for
// - performance reasons
// - avoids sending additional headers (Expires, Cache-Control, Pragma) that get attached when you run session_start()
// set it to 'true' when using url_mode=3
$config['session_enable'] = false;

// By default: PHP will append "X-Powered-By" to your own list of headers
$config['expose_php'] = true;

// plugins to load - plugins will be loaded in this exact order as in array
$config['plugins'] = array(
    \Proxy\Plugin\HeaderRewritePlugin::class,
    \Proxy\Plugin\StreamPlugin::class,
    // ^^ do not disable any of the plugins above
    'YouTube', // YouTube-specific fixes for modern interface
    'Cookie',
    'Proxify',
    'UrlForm'
);

// additional curl options to go with each request
$config['curl'] = array(
    // CURLOPT_PROXY => '',
    // CURLOPT_CONNECTTIMEOUT => 5
    CURLOPT_USERAGENT => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
    CURLOPT_HTTPHEADER => array(
        'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
        'Accept-Language: en-US,en;q=0.9',
        'Accept-Encoding: gzip, deflate, br',
        'Cache-Control: max-age=0',
        'Sec-Ch-Ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"',
        'Sec-Ch-Ua-Mobile: ?0',
        'Sec-Ch-Ua-Platform: "Windows"',
        'Sec-Fetch-Dest: document',
        'Sec-Fetch-Mode: navigate',
        'Sec-Fetch-Site: none',
        'Sec-Fetch-User: ?1',
        'Upgrade-Insecure-Requests: 1'
    ),
    CURLOPT_ENCODING => '', // enable all supported encodings (gzip, deflate, br)
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_MAXREDIRS => 10,
);

//$config['replace_title'] = 'Google Search';

//$config['error_redirect'] = "https://unblockvideos.com/#error={error_msg}";
//$config['index_redirect'] = 'https://unblockvideos.com/';

// $config['replace_icon'] = 'icon_url';

// this better be here other Config::load fails
return $config;
